// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var TodoApp$ReactHooksTemplate = require("./TodoApp.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(TodoApp$ReactHooksTemplate.make, { }), "todo-app");

/*  Not a pure module */
