// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function ItemsList(Props) {
  var showing = Props.showing;
  return React.createElement("div", undefined, React.createElement("h1", undefined, showing));
}

var make = ItemsList;

exports.make = make;
/* react Not a pure module */
